import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const client = await readFile(new URL('../script.js', import.meta.url), 'utf8');
const server = await readFile(new URL('../dist/server/index.js', import.meta.url), 'utf8');
const bridge = await readFile(new URL('../api/_bridge.js', import.meta.url), 'utf8');
const page = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const compactClient = await readFile(new URL('../src/midnight-client.js', import.meta.url), 'utf8');
const contract = await readFile(new URL('../contract/src/aletheia.compact', import.meta.url), 'utf8');
test('no reusable wallet identifier is uploaded', () => { assert.doesNotMatch(client, /walletId/); assert.doesNotMatch(server, /body\.walletId|wallet_id/); assert.match(server, /claim_records/); });
test('duplicate guard is program scoped', () => { assert.match(client, /aletheia-simulation-nullifier-v1:\$\{programId\}/); assert.match(contract, /deriveProgramNullifier\(secret: UserSecret, programId/); assert.match(server, /idx_claim_records_program_nullifier/); });
test('metrics report explicit attempt and inventory totals', () => { assert.match(server, /attemptedClaims = validClaims \+ duplicateClaimsStopped/); assert.match(server, /remainingSupplies/); assert.doesNotMatch(server, /protocolSuccess/); });
test('inventory is atomically capped', () => { assert.match(server, /trg_claim_records_capacity_guard/); assert.match(server, /PROGRAM_CAPACITY_REACHED/); assert.match(server, /PROGRAM_FULL/); });
test('bridge uses server-only bearer authorization', () => { assert.match(bridge, /OAI-Sites-Authorization/); assert.match(bridge, /Bearer \$\{SITES_TOKEN\}/); });
test('page labels simulation and Compact modes honestly', () => { assert.match(page, /Clearly labeled simulation/i); assert.match(page, /Compact only succeeds with a deployed Preprod contract/i); });
test('Midnight flow submits a Compact call and records evidence', () => { assert.match(compactClient, /submitCallTx/); assert.match(compactClient, /circuitId: 'claim'/); assert.match(compactClient, /submitTransaction/); assert.match(server, /compact_verified/); assert.match(server, /contract_address/); });
test('unfinished reservations expire and release inventory', () => { assert.match(server, /reserved_until/); assert.match(server, /status = 'expired'/); assert.match(server, /trg_claim_records_release_v2/); });
test('raw eligibility answers are absent from claim API payload', () => { const payload = client.match(/JSON\.stringify\(\{ programId, nullifier, commitment, proofMode:[^}]+\}\)/)?.[0] || ''; assert.ok(payload); assert.doesNotMatch(payload, /age|income|household|jurisdiction/); });
test('contract enforces issuer signature and revocation', () => { assert.match(contract, /schnorrVerify/); assert.match(contract, /providers\.member/); assert.match(contract, /revokedCredentials\.member/); });
test('contract enforces all private policy predicates', () => { for (const field of ['age >= policy.minAge','jurisdiction == policy.jurisdiction','householdSize >= policy.minHouseholdSize','annualIncome <= policy.maxAnnualIncome']) assert.match(contract, new RegExp(field.replaceAll('.', '\\.'))); });
test('three unlinkable programs are exposed', () => { for (const id of ['food-support-2026','medical-assistance-2026','temporary-shelter-2026']) { assert.match(page, new RegExp(id)); assert.match(server, new RegExp(id)); } });
